### ISSUE TITLE
v2.0.8 getGranularity returns 'NoneType'

### ISSUE THREAD

**Issue by p9qgtjaliucdtygqapv79h5nm1faov8** [whittlem/pycryptobot#177]
**Describe the bug**
Error reading the granularity when launching.
Most likely a error reading the config file.

**To Reproduce**
docker-compose.yml
```
  pycryptobot_btc:
    image: ghcr.io/whittlem/pycryptobot/pycryptobot:latest
    container_name: pycryptobot_btc
    volumes:
      - ./market/btc-usd/config.json:/app/config.json
      - ./market/btc-usd/pycryptobot.log:/app/pycryptobot.log
      - ./market/btc-usd/graphs:/app/graphs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      restart_policy:
        condition: on-failure
```

config.json
```
{
    "api_url" : "https://api.pro.coinbase.com",
    "api_key" : "...",
    "api_secret" : "...",
    "api_pass" : "...",
    "config" : {
        "base_currency" : "BTC",
        "quote_currency" : "USD",
        "live" : 1,
        "verbose" : 0,
        "sellatloss" : 0
    }
}
```

**Expected behavior**
I expected the bot to use automatic granularity since it is not specified in the config.json.

**Screenshots**
```
--------------------------------------------------------------------------------
|                             Python Crypto Bot                                |
--------------------------------------------------------------------------------
|               Release :                                                      |
--------------------------------------------------------------------------------
|              Bot Mode : TEST - test trades using dummy funds :)              |
|           Bot Started : 2021-05-13 12:12:21.649132                           |
================================================================================
|          Sell At Loss : True  --sellatloss 1                                 |
|    Sell At Resistance : False  --sellatresistance                            |
|       Trade Bull Only : True  --disablebullonly                              |
|         Buy Near High : True  --disablebuynearhigh                           |
|          Use Buy MACD : True  --disablebuymacd                               |
|           Use Buy OBV : True  --disablebuyobv                                |
|     Use Buy Elder-Ray : True  --disablebuyelderray                           |
|    Sell Fibonacci Low : True  --disablefailsafefibonaccilow                  |
|  Candlestick Reversal : True  --disableprofitbankreversal                    |
|              Telegram : True  --disabletelegram                              |
|                   Log : True  --disablelog                                   |
|               Tracker : True  --disabletracker                               |
|      Auto restart Bot : False  --autorestart                                 |
================================================================================
TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'")
Traceback (most recent call last):
  File "/app/pycryptobot.py", line 1095, in <module>
    main()
  File "/app/pycryptobot.py", line 1058, in main
    runApp()
  File "/app/pycryptobot.py", line 1053, in runApp
    executeJob(s, app, state)
  File "/app/pycryptobot.py", line 232, in executeJob
    trading_data = app.getHistoricalData(app.getMarket(), app.getGranularity())
  File "/app/models/PyCryptoBot.py", line 212, in getGranularity
    return int(self.granularity)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Docker (please complete the following information):**
 - Host OS: Debian
 - Bot Version: 2.0.8
 - Market: Coinbase Pro

**Additional context**
Bot runs fine on 2.0.7 and lower with the same config.json and docer-compose.yml.
