### ISSUE TITLE
Suggestion: Configurable log file names

### ISSUE THREAD

**Issue by github-ptaylor** [whittlem/pycryptobot#82]
Hey Mike,

While troubleshooting my issue ([#80](https://github.com/whittlem/pycryptobot/issues/80)), I thought on the idea of being able to use a log file name that had the (market pair) in the name. i.e. (pycrypto-ETHUSDT.log).

This hack is handy if you are running multiple bots under one install using subprocesses.

So, i got it working on my version of the code base:

**[config.json]** 
- adding a new key to the (config) array

`"logfile_prefix" : ""`

**[models/PyCryptoBot.py]**
- added a default configuration value in case the key does not exist in the (config.json) file.
- added logic to check for key in config file and to scrub it and use it.

`self.logfile_prefix = 'pycryptobot'`

```
if 'logfile_prefix' in config:
     if isinstance(config['logfile_prefix'], str):
        self.logfile_prefix = config['logfile_prefix'].strip()
        if self.logfile_prefix == "":
           self.logfile_prefix = "pycryptobot"
        else:
           self.logfile_prefix = config['logfile_prefix']
```

**[pycryptobot.py]**
- added new variable (logfile_name)
- set variable to to use (logfile_prefix) property concatenated with (market) value and hardcoded file extension
- the file extension can be made configurable as well
- logic could be added to pre-pend a date string before the file extension

```
try:
    # initialise logging
    log_filename = app.logfile_prefix + "-" + app.getMarket() + ".log"
    logging.basicConfig(filename=log_filename, format='%(asctime)s - %(levelname)s: %(message)s', datefmt='%m/%d/%Y %I:%M:%S %p', filemode='a', level=logging.DEBUG)
```

---

Here are examples of the files created using the logic

-rw-r--r--   1 admin  staff   3519 Apr 28 14:21 pycryptobot-ADAUSDT.log
-rw-r--r--   1 admin  staff   3464 Apr 28 14:21 pycryptobot-ETHUSDT.log

--

**Comment by letsautom8** [comment]
Good suggestion. Though this might not be ideal for dockerised bot. Another approach is to pass the log filename as a parameter OR mount the logs on docker-compose like the one below

Option 1: No code change, run bot on docker
```
version: "3.9"

services:
  # coinbase pro
  ethdai:
    image: pycryptobot
    container_name: ETHDAI
    volumes:
      - ./market/ETHDAI/config.json:/app/config.json
      - ./market/ETHDAI/pycryptobot.log:/app/pycryptobot.log
      - ./market/ETHDAI/graphs:/app/graphs
      - /etc/localtime:/etc/localtime:ro
    deploy:
      restart_policy:
        condition: on-failure
  
  btcdai:
    image: pycryptobot
    container_name: btcdai
    volumes:
      - ./market/BTCDAI/config.json:/app/config.json
      - ./market/BTCDAI/pycryptobot.log:/app/pycryptobot.log
      - ./market/BTCDAI/graphs:/app/graphs
      - /etc/localtime:/etc/localtime:ro
    deploy:
      restart_policy:
        condition: on-failure
```

Option 2: Code change neeed, pass the logfile as parameter or as environment variable
```
python3 pycryptobot.py --market BTC-GBP --granularity 3600 --live 1 --verbose 0 --selllowerpcnt -2 --logfile ./btc-gbp.log
```

inside docker-compose.yml
```
version: "3.9"

services:
  # coinbase pro
  ethdai:
    image: pycryptobot
    container_name: ETHDAI
    volumes:
      - ./market/ETHDAI/config.json:/app/config.json
      - ./market/ETHDAI/graphs:/app/graphs
      - /etc/localtime:/etc/localtime:ro
    environment:
     - LOGFILE:btc-gbp.log
    deploy:
      restart_policy:
        condition: on-failure
  
  btcdai:
    image: pycryptobot
    container_name: btcdai
    volumes:
      - ./market/BTCDAI/config.json:/app/config.json
      - ./market/BTCDAI/graphs:/app/graphs
      - /etc/localtime:/etc/localtime:ro
   environment:
     - LOGFILE:eth-dai.log
    deploy:
      restart_policy:
        condition: on-failure
```

@whittlem would u like me to work on this one?
